server:
  port: 8080
spring:
  r2dbc:
    username: root
    password: password
    url: r2dbc:postgresql://localhost:5432/webflux
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: true
    baseline-on-migrate: true
jwt:
  password:
    encoder:
      secret: secret
      iteration: 33
      keylength: 256